# local_topological_descriptors = list[list[tplgcl_dscrptr, eeel_ntwrk, save_result, return_result]]
# type(local_topological_descriptors) = list[list[str, bool, bool, bool]]
# global_topological_descriptors = list[list[tplgcl_dscrptr, np_oprtn, eeel_ntwrk, save_result, return_result]]
# type(global_topological_descriptors) = list[list[str, str, bool, bool, bool]]
# global_morphological_descriptors = list[list[mrphlgcl_dscrptr, save_result, return_result]]
# type(global_morphological_descriptors) = list[list[str, bool, bool]]
local_topological_descriptors:
  -
    - "k"
    - True
    - True
    - False
  -
    - "avrg_nn_k"
    - True
    - True
    - False
  -
    - "avrg_k_diff"
    - True
    - True
    - False
  -
    - "c"
    - True
    - True
    - False
  -
    - "lcl_avrg_kappa"
    - True
    - True
    - False
  -
    - "epsilon"
    - True
    - True
    - False
  -
    - "l_attr_epsilon"
    - True
    - True
    - False
  -
    - "l_inv_attr_epsilon"
    - True
    - True
    - False
  -
    - "gamma_attr_epsilon"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_epsilon"
    - True
    - True
    - False
  -
    - "avrg_d"
    - True
    - True
    - False
  -
    - "avrg_l_attr_d"
    - True
    - True
    - False
  -
    - "avrg_l_inv_attr_d"
    - True
    - True
    - False
  -
    - "avrg_gamma_attr_d"
    - True
    - True
    - False
  -
    - "avrg_gamma_inv_attr_d"
    - True
    - True
    - False
  -
    - "avrg_e"
    - True
    - True
    - False
  -
    - "avrg_l_attr_e"
    - True
    - True
    - False
  -
    - "avrg_l_inv_attr_e"
    - True
    - True
    - False
  -
    - "avrg_gamma_attr_e"
    - True
    - True
    - False
  -
    - "avrg_gamma_inv_attr_e"
    - True
    - True
    - False
  -
    - "bc"
    - True
    - True
    - False
  -
    - "l_attr_bc"
    - True
    - True
    - False
  -
    - "l_inv_attr_bc"
    - True
    - True
    - False
  -
    - "gamma_attr_bc"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_bc"
    - True
    - True
    - False
  -
    - "cc"
    - True
    - True
    - False
  -
    - "l_attr_cc"
    - True
    - True
    - False
  -
    - "l_inv_attr_cc"
    - True
    - True
    - False
  -
    - "gamma_attr_cc"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_cc"
    - True
    - True
    - False
  -
    - "l"
    - True
    - True
    - False
  -
    - "l_inv"
    - True
    - True
    - False
  -
    - "l_cmpnts"
    - True
    - True
    - False
  -
    - "l_naive"
    - True
    - True
    - False
  -
    - "l_cntr"
    - True
    - True
    - False
  -
    - "gamma"
    - True
    - True
    - False
  -
    - "gamma_inv"
    - True
    - True
    - False
  -
    - "k_diff"
    - True
    - True
    - False
  -
    - "ebc"
    - True
    - True
    - False
  -
    - "l_attr_ebc"
    - True
    - True
    - False
  -
    - "l_inv_attr_ebc"
    - True
    - True
    - False
  -
    - "gamma_attr_ebc"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_ebc"
    - True
    - True
    - False
global_topological_descriptors:
  -
    - "n"
    - ""
    - True
    - True
    - False
  -
    - "m"
    - ""
    - True
    - True
    - False
  -
    - "r"
    - ""
    - True
    - True
    - False
  -
    - "sigma"
    - ""
    - True
    - True
    - False
  -
    - "prop_eeel_n"
    - ""
    - False
    - True
    - False
  -
    - "prop_eeel_m"
    - ""
    - False
    - True
    - False
  -
    - "rho_graph"
    - ""
    - True
    - True
    - False
  -
    - "glbl_avrg_kappa"
    - ""
    - True
    - True
    - False
  -
    - "lambda_1"
    - ""
    - True
    - True
    - False
  -
    - "r_pearson"
    - ""
    - True
    - True
    - False
  -
    - "l_attr_r"
    - ""
    - True
    - True
    - False
  -
    - "l_inv_attr_r"
    - ""
    - True
    - True
    - False
  -
    - "gamma_attr_r"
    - ""
    - True
    - True
    - False
  -
    - "gamma_inv_attr_r"
    - ""
    - True
    - True
    - False
  -
    - "l_attr_sigma"
    - ""
    - True
    - True
    - False
  -
    - "l_inv_attr_sigma"
    - ""
    - True
    - True
    - False
  -
    - "gamma_attr_sigma"
    - ""
    - True
    - True
    - False
  -
    - "gamma_inv_attr_sigma"
    - ""
    - True
    - True
    - False
  -
    - "l"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv"
    - "mean"
    - True
    - True
    - False
  -
    - "l_cmpnts"
    - "mean"
    - True
    - True
    - False
  -
    - "l_naive"
    - "mean"
    - True
    - True
    - False
  -
    - "l_cntr"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv"
    - "mean"
    - True
    - True
    - False
  -
    - "k"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_nn_k"
    - "mean"
    - True
    - True
    - False
  -
    - "k_diff"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_k_diff"
    - "mean"
    - True
    - True
    - False
  -
    - "c"
    - "mean"
    - True
    - True
    - False
  -
    - "kappa"
    - "mean"
    - True
    - True
    - False
  -
    - "lcl_avrg_kappa"
    - "mean"
    - True
    - True
    - False
  -
    - "epsilon"
    - "mean"
    - True
    - True
    - False
  -
    - "l_attr_epsilon"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv_attr_epsilon"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_attr_epsilon"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_epsilon"
    - "mean"
    - True
    - True
    - False
  -
    - "d"
    - "mean"
    - True
    - True
    - False
  -
    - "l_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_d"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_l_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_l_inv_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_gamma_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_gamma_inv_attr_d"
    - "mean"
    - True
    - True
    - False
  -
    - "e"
    - "mean"
    - True
    - True
    - False
  -
    - "l_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_e"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_l_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_l_inv_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_gamma_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "avrg_gamma_inv_attr_e"
    - "mean"
    - True
    - True
    - False
  -
    - "bc"
    - "mean"
    - True
    - True
    - False
  -
    - "l_attr_bc"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv_attr_bc"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_attr_bc"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_bc"
    - "mean"
    - True
    - True
    - False
  -
    - "ebc"
    - "mean"
    - True
    - True
    - False
  -
    - "l_attr_ebc"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv_attr_ebc"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_attr_ebc"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_ebc"
    - "mean"
    - True
    - True
    - False
  -
    - "cc"
    - "mean"
    - True
    - True
    - False
  -
    - "l_attr_cc"
    - "mean"
    - True
    - True
    - False
  -
    - "l_inv_attr_cc"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_attr_cc"
    - "mean"
    - True
    - True
    - False
  -
    - "gamma_inv_attr_cc"
    - "mean"
    - True
    - True
    - False
global_morphological_descriptors:
  -
    - "xi_corr"
    - True
    - False
  -
    - "n_fractal_dim"
    - True
    - False